name: DgMCMod
main: top.DrakGod.DgMCMod.Main
version: Beta1.0
api: "1.20"
description: 这是一个专门为DgMC打造的插件
authors: [Drakgod]
website: https://dgmc.drakgod.top
depend: [ItemsAdder]

commands:
  music:
    description: 打开音乐菜单
    usage: /music
    permission: dgmc.music
    aliases: [m]