info:
  namespace: dgmcmod
sounds:
  billie_jean:
    sound: music.billie_jean
    category: music
    pitch: 1.0
    volume: 1.0
  cry_for_me:
    sound: music.cry_for_me
    category: music
    pitch: 1.0
    volume: 1.0
  lush_life_x_paradise:
    sound: music.lush_life_x_paradise
    category: music
    pitch: 1.0
    volume: 1.0
  naive_eraser:
    sound: music.naive_eraser
    category: music
    pitch: 1.0
    volume: 1.0
  sos:
    sound: music.sos
    category: music
    pitch: 1.0
    volume: 1.0